/* eslint-disable @typescript-eslint/no-require-imports */
export const ART = {
  cells: [
    require("../../assets/art/cell0.png"), require("../../assets/art/cell1.png"), require("../../assets/art/cell2.png"),
    require("../../assets/art/cell3.png"), require("../../assets/art/cell4.png"),
  ],
  wild: require("../../assets/art/cell_wild.png"),
  bomb: require("../../assets/art/bomb.png"),
  ring: require("../../assets/art/ring.png"),
  comb: require("../../assets/art/comb.png"),
  combEmpty: require("../../assets/art/comb_empty.png"),
  combLocked: require("../../assets/art/comb_locked.png"),
  honey: require("../../assets/art/honey.png"),
  jelly: require("../../assets/art/jelly.png"),
  star: require("../../assets/art/star.png"),
  starOff: require("../../assets/art/star_off.png"),
  flame: require("../../assets/art/flame.png"),
  chest: require("../../assets/art/chest.png"),
  check: require("../../assets/art/check.png"),
  drop: require("../../assets/art/drop.png"),
  bgTile: require("../../assets/art/bg_tile.png"),
  tabHive: require("../../assets/art/tab_hive.png"),
  tabPuzzle: require("../../assets/art/tab_puzzle.png"),
  tabBee: require("../../assets/art/tab_bee.png"),
  tabTasks: require("../../assets/art/tab_tasks.png"),
  gear: require("../../assets/art/gear.png"),
  lock: require("../../assets/art/lock.png"),
  close: require("../../assets/art/close.png"),
  clock: require("../../assets/art/clock.png"),
};

export const BEE_ART: Record<string, number> = {
  zhuzha: require("../../assets/art/bee_zhuzha.png"),
  pushinka: require("../../assets/art/bee_pushinka.png"),
  boris: require("../../assets/art/bee_boris.png"),
  solnyshko: require("../../assets/art/bee_solnyshko.png"),
  klevera: require("../../assets/art/bee_klevera.png"),
  lavanda: require("../../assets/art/bee_lavanda.png"),
  vasilek: require("../../assets/art/bee_vasilek.png"),
  myatka: require("../../assets/art/bee_myatka.png"),
  iskorka: require("../../assets/art/bee_iskorka.png"),
  sonya: require("../../assets/art/bee_sonya.png"),
  zorkaya: require("../../assets/art/bee_zorkaya.png"),
  margo: require("../../assets/art/bee_margo.png"),
};
