/* AUTO-GENERATED by scripts/bees3d/pack.py from the Blender renders (scripts/bees3d/render_lowpoly.py). Do not edit. */
/* eslint-disable @typescript-eslint/no-require-imports */
export type Rect = [number, number, number, number]; // x, y, w, h as fractions of the render frame
export type Layer = [number, Rect];
export interface BeeView { yaw: number; body: Layer; eyes?: Layer; pivotL: [number, number]; pivotR: [number, number] }
export interface SharedView { wingL: Layer; wingR: Layer; goldL: Layer; goldR: Layer; crown: Layer; pivotL: [number, number]; pivotR: [number, number] }
const R0 = require("../../assets/art/bees/zhuzha_0_body.webp");
const R1 = require("../../assets/art/bees/zhuzha_0_eyes.webp");
const R2 = require("../../assets/art/bees/zhuzha_16_body.webp");
const R3 = require("../../assets/art/bees/zhuzha_16_eyes.webp");
const R4 = require("../../assets/art/bees/zhuzha_32_body.webp");
const R5 = require("../../assets/art/bees/zhuzha_32_eyes.webp");
const R6 = require("../../assets/art/bees/zhuzha_47_body.webp");
const R7 = require("../../assets/art/bees/zhuzha_47_eyes.webp");
const R8 = require("../../assets/art/bees/zhuzha_62_body.webp");
const R9 = require("../../assets/art/bees/zhuzha_62_eyes.webp");
const R10 = require("../../assets/art/bees/pushinka_0_body.webp");
const R11 = require("../../assets/art/bees/pushinka_0_eyes.webp");
const R12 = require("../../assets/art/bees/pushinka_32_body.webp");
const R13 = require("../../assets/art/bees/pushinka_32_eyes.webp");
const R14 = require("../../assets/art/bees/pushinka_62_body.webp");
const R15 = require("../../assets/art/bees/pushinka_62_eyes.webp");
const R16 = require("../../assets/art/bees/boris_0_body.webp");
const R17 = require("../../assets/art/bees/boris_0_eyes.webp");
const R18 = require("../../assets/art/bees/boris_32_body.webp");
const R19 = require("../../assets/art/bees/boris_32_eyes.webp");
const R20 = require("../../assets/art/bees/boris_62_body.webp");
const R21 = require("../../assets/art/bees/boris_62_eyes.webp");
const R22 = require("../../assets/art/bees/solnyshko_0_body.webp");
const R23 = require("../../assets/art/bees/solnyshko_0_eyes.webp");
const R24 = require("../../assets/art/bees/solnyshko_32_body.webp");
const R25 = require("../../assets/art/bees/solnyshko_32_eyes.webp");
const R26 = require("../../assets/art/bees/solnyshko_62_body.webp");
const R27 = require("../../assets/art/bees/solnyshko_62_eyes.webp");
const R28 = require("../../assets/art/bees/klevera_0_body.webp");
const R29 = require("../../assets/art/bees/klevera_0_eyes.webp");
const R30 = require("../../assets/art/bees/klevera_32_body.webp");
const R31 = require("../../assets/art/bees/klevera_32_eyes.webp");
const R32 = require("../../assets/art/bees/klevera_62_body.webp");
const R33 = require("../../assets/art/bees/klevera_62_eyes.webp");
const R34 = require("../../assets/art/bees/lavanda_0_body.webp");
const R35 = require("../../assets/art/bees/lavanda_0_eyes.webp");
const R36 = require("../../assets/art/bees/lavanda_32_body.webp");
const R37 = require("../../assets/art/bees/lavanda_32_eyes.webp");
const R38 = require("../../assets/art/bees/lavanda_62_body.webp");
const R39 = require("../../assets/art/bees/lavanda_62_eyes.webp");
const R40 = require("../../assets/art/bees/vasilek_0_body.webp");
const R41 = require("../../assets/art/bees/vasilek_0_eyes.webp");
const R42 = require("../../assets/art/bees/vasilek_32_body.webp");
const R43 = require("../../assets/art/bees/vasilek_32_eyes.webp");
const R44 = require("../../assets/art/bees/vasilek_62_body.webp");
const R45 = require("../../assets/art/bees/vasilek_62_eyes.webp");
const R46 = require("../../assets/art/bees/myatka_0_body.webp");
const R47 = require("../../assets/art/bees/myatka_0_eyes.webp");
const R48 = require("../../assets/art/bees/myatka_32_body.webp");
const R49 = require("../../assets/art/bees/myatka_32_eyes.webp");
const R50 = require("../../assets/art/bees/myatka_62_body.webp");
const R51 = require("../../assets/art/bees/myatka_62_eyes.webp");
const R52 = require("../../assets/art/bees/iskorka_0_body.webp");
const R53 = require("../../assets/art/bees/iskorka_0_eyes.webp");
const R54 = require("../../assets/art/bees/iskorka_32_body.webp");
const R55 = require("../../assets/art/bees/iskorka_32_eyes.webp");
const R56 = require("../../assets/art/bees/iskorka_62_body.webp");
const R57 = require("../../assets/art/bees/iskorka_62_eyes.webp");
const R58 = require("../../assets/art/bees/sonya_0_body.webp");
const R59 = require("../../assets/art/bees/sonya_32_body.webp");
const R60 = require("../../assets/art/bees/sonya_62_body.webp");
const R61 = require("../../assets/art/bees/zorkaya_0_body.webp");
const R62 = require("../../assets/art/bees/zorkaya_0_eyes.webp");
const R63 = require("../../assets/art/bees/zorkaya_32_body.webp");
const R64 = require("../../assets/art/bees/zorkaya_32_eyes.webp");
const R65 = require("../../assets/art/bees/zorkaya_62_body.webp");
const R66 = require("../../assets/art/bees/zorkaya_62_eyes.webp");
const R67 = require("../../assets/art/bees/margo_0_body.webp");
const R68 = require("../../assets/art/bees/margo_0_eyes.webp");
const R69 = require("../../assets/art/bees/margo_32_body.webp");
const R70 = require("../../assets/art/bees/margo_32_eyes.webp");
const R71 = require("../../assets/art/bees/margo_62_body.webp");
const R72 = require("../../assets/art/bees/margo_62_eyes.webp");
const R73 = require("../../assets/art/bees/shared_62_wingL.webp");
const R74 = require("../../assets/art/bees/shared_62_wingR.webp");
const R75 = require("../../assets/art/bees/shared_62_goldL.webp");
const R76 = require("../../assets/art/bees/shared_62_goldR.webp");
const R77 = require("../../assets/art/bees/shared_62_crown.webp");
const R78 = require("../../assets/art/bees/shared_32_wingL.webp");
const R79 = require("../../assets/art/bees/shared_32_wingR.webp");
const R80 = require("../../assets/art/bees/shared_32_goldL.webp");
const R81 = require("../../assets/art/bees/shared_32_goldR.webp");
const R82 = require("../../assets/art/bees/shared_32_crown.webp");
const R83 = require("../../assets/art/bees/shared_0_wingL.webp");
const R84 = require("../../assets/art/bees/shared_0_wingR.webp");
const R85 = require("../../assets/art/bees/shared_0_goldL.webp");
const R86 = require("../../assets/art/bees/shared_0_goldR.webp");
const R87 = require("../../assets/art/bees/shared_0_crown.webp");
const R88 = require("../../assets/art/bees/shared_16_wingL.webp");
const R89 = require("../../assets/art/bees/shared_16_wingR.webp");
const R90 = require("../../assets/art/bees/shared_16_goldL.webp");
const R91 = require("../../assets/art/bees/shared_16_goldR.webp");
const R92 = require("../../assets/art/bees/shared_16_crown.webp");
const R93 = require("../../assets/art/bees/shared_47_wingL.webp");
const R94 = require("../../assets/art/bees/shared_47_wingR.webp");
const R95 = require("../../assets/art/bees/shared_47_goldL.webp");
const R96 = require("../../assets/art/bees/shared_47_goldR.webp");
const R97 = require("../../assets/art/bees/shared_47_crown.webp");
export const BEE_VIEWS: Record<string, BeeView[]> = {
  zhuzha: [
    { yaw: 0, body: [R0, [0.2188, 0.0703, 0.5625, 0.9062]], eyes: [R1, [0.3411, 0.4818, 0.3177, 0.1146]], pivotL: [0.3691, 0.3935], pivotR: [0.6309, 0.3935] },
    { yaw: 16, body: [R2, [0.2135, 0.0677, 0.5729, 0.9089]], eyes: [R3, [0.4089, 0.4766, 0.3047, 0.1224]], pivotL: [0.3454, 0.3982], pivotR: [0.5977, 0.3898] },
    { yaw: 32, body: [R4, [0.2188, 0.0651, 0.5547, 0.9115]], eyes: [R5, [0.4844, 0.4688, 0.276, 0.1328]], pivotL: [0.3331, 0.4036], pivotR: [0.5575, 0.3873] },
    { yaw: 47, body: [R6, [0.2292, 0.0651, 0.5495, 0.9115]], eyes: [R7, [0.5521, 0.4609, 0.237, 0.138]], pivotL: [0.3332, 0.4088], pivotR: [0.5161, 0.3862] },
    { yaw: 62, body: [R8, [0.2292, 0.0625, 0.5391, 0.9141]], eyes: [R9, [0.6146, 0.4531, 0.1823, 0.1406]], pivotL: [0.3449, 0.4139], pivotR: [0.4737, 0.3864] },
  ],
  pushinka: [
    { yaw: 0, body: [R10, [0.2148, 0.0703, 0.5664, 0.9062]], eyes: [R11, [0.3398, 0.4805, 0.3203, 0.1211]], pivotL: [0.3691, 0.3936], pivotR: [0.6309, 0.3936] },
    { yaw: 32, body: [R12, [0.2148, 0.0625, 0.5977, 0.9141]], eyes: [R13, [0.4805, 0.4688, 0.2812, 0.1328]], pivotL: [0.3331, 0.4036], pivotR: [0.5575, 0.3873] },
    { yaw: 62, body: [R14, [0.2266, 0.0586, 0.5703, 0.9219]], eyes: [R15, [0.6133, 0.4531, 0.1875, 0.1406]], pivotL: [0.3449, 0.4139], pivotR: [0.4738, 0.3864] },
  ],
  boris: [
    { yaw: 0, body: [R16, [0.1797, 0.0703, 0.6406, 0.9062]], eyes: [R17, [0.3398, 0.4844, 0.3203, 0.1211]], pivotL: [0.3508, 0.3936], pivotR: [0.6492, 0.3936] },
    { yaw: 32, body: [R18, [0.1797, 0.0625, 0.6289, 0.9141]], eyes: [R19, [0.4922, 0.4688, 0.2812, 0.1367]], pivotL: [0.3169, 0.4047], pivotR: [0.5727, 0.3862] },
    { yaw: 62, body: [R20, [0.1992, 0.0586, 0.5977, 0.9219]], eyes: [R21, [0.6289, 0.4531, 0.1914, 0.1445]], pivotL: [0.3354, 0.4159], pivotR: [0.4823, 0.3845] },
  ],
  solnyshko: [
    { yaw: 0, body: [R22, [0.2148, 0.0703, 0.5664, 0.9062]], eyes: [R23, [0.3398, 0.4805, 0.3203, 0.1211]], pivotL: [0.3691, 0.3936], pivotR: [0.6309, 0.3936] },
    { yaw: 32, body: [R24, [0.2148, 0.0625, 0.5664, 0.9141]], eyes: [R25, [0.4805, 0.4688, 0.2812, 0.1328]], pivotL: [0.3331, 0.4036], pivotR: [0.5575, 0.3873] },
    { yaw: 62, body: [R26, [0.2266, 0.0586, 0.543, 0.9219]], eyes: [R27, [0.6133, 0.4531, 0.1875, 0.1406]], pivotL: [0.3449, 0.4139], pivotR: [0.4738, 0.3864] },
  ],
  klevera: [
    { yaw: 0, body: [R28, [0.2148, 0.0703, 0.5664, 0.9062]], eyes: [R29, [0.3398, 0.4805, 0.3203, 0.1211]], pivotL: [0.3691, 0.3936], pivotR: [0.6309, 0.3936] },
    { yaw: 32, body: [R30, [0.2148, 0.0625, 0.5625, 0.9141]], eyes: [R31, [0.4805, 0.4688, 0.2812, 0.1328]], pivotL: [0.3331, 0.4036], pivotR: [0.5575, 0.3873] },
    { yaw: 62, body: [R32, [0.2266, 0.0586, 0.543, 0.9219]], eyes: [R33, [0.6133, 0.4531, 0.1875, 0.1406]], pivotL: [0.3449, 0.4139], pivotR: [0.4738, 0.3864] },
  ],
  lavanda: [
    { yaw: 0, body: [R34, [0.2148, 0.0703, 0.5664, 0.9062]], eyes: [R35, [0.3398, 0.4805, 0.3203, 0.1211]], pivotL: [0.3691, 0.3936], pivotR: [0.6309, 0.3936] },
    { yaw: 32, body: [R36, [0.2148, 0.0625, 0.5664, 0.9141]], eyes: [R37, [0.4805, 0.4688, 0.2812, 0.1328]], pivotL: [0.3331, 0.4036], pivotR: [0.5575, 0.3873] },
    { yaw: 62, body: [R38, [0.2266, 0.0586, 0.543, 0.9219]], eyes: [R39, [0.6133, 0.4531, 0.1875, 0.1406]], pivotL: [0.3449, 0.4139], pivotR: [0.4738, 0.3864] },
  ],
  vasilek: [
    { yaw: 0, body: [R40, [0.2148, 0.0703, 0.5664, 0.9062]], eyes: [R41, [0.3398, 0.4805, 0.3203, 0.1211]], pivotL: [0.3691, 0.3936], pivotR: [0.6309, 0.3936] },
    { yaw: 32, body: [R42, [0.2148, 0.0625, 0.5625, 0.9141]], eyes: [R43, [0.4805, 0.4688, 0.2812, 0.1328]], pivotL: [0.3331, 0.4036], pivotR: [0.5575, 0.3873] },
    { yaw: 62, body: [R44, [0.2266, 0.0586, 0.543, 0.9219]], eyes: [R45, [0.6133, 0.4531, 0.1875, 0.1406]], pivotL: [0.3449, 0.4139], pivotR: [0.4738, 0.3864] },
  ],
  myatka: [
    { yaw: 0, body: [R46, [0.2148, 0.0703, 0.5664, 0.9062]], eyes: [R47, [0.3398, 0.4805, 0.3203, 0.1211]], pivotL: [0.3691, 0.3936], pivotR: [0.6309, 0.3936] },
    { yaw: 32, body: [R48, [0.2148, 0.0625, 0.5625, 0.9141]], eyes: [R49, [0.4805, 0.4688, 0.2812, 0.1328]], pivotL: [0.3331, 0.4036], pivotR: [0.5575, 0.3873] },
    { yaw: 62, body: [R50, [0.2266, 0.0586, 0.543, 0.9219]], eyes: [R51, [0.6133, 0.4531, 0.1875, 0.1406]], pivotL: [0.3449, 0.4139], pivotR: [0.4738, 0.3864] },
  ],
  iskorka: [
    { yaw: 0, body: [R52, [0.2148, 0.0234, 0.5664, 0.9531]], eyes: [R53, [0.3398, 0.4805, 0.3203, 0.1211]], pivotL: [0.3691, 0.3936], pivotR: [0.6309, 0.3936] },
    { yaw: 32, body: [R54, [0.2148, 0.0195, 0.5625, 0.957]], eyes: [R55, [0.4805, 0.4688, 0.2812, 0.1328]], pivotL: [0.3331, 0.4036], pivotR: [0.5575, 0.3873] },
    { yaw: 62, body: [R56, [0.2266, 0.0156, 0.543, 0.9648]], eyes: [R57, [0.6133, 0.4531, 0.1875, 0.1406]], pivotL: [0.3449, 0.4139], pivotR: [0.4738, 0.3864] },
  ],
  sonya: [
    { yaw: 0, body: [R58, [0.2148, 0.0586, 0.5664, 0.918]], pivotL: [0.3691, 0.3936], pivotR: [0.6309, 0.3936] },
    { yaw: 32, body: [R59, [0.2148, 0.0547, 0.5625, 0.9219]], pivotL: [0.3331, 0.4036], pivotR: [0.5575, 0.3873] },
    { yaw: 62, body: [R60, [0.2266, 0.0469, 0.5508, 0.9336]], pivotL: [0.3449, 0.4139], pivotR: [0.4738, 0.3864] },
  ],
  zorkaya: [
    { yaw: 0, body: [R61, [0.2148, 0.0703, 0.5664, 0.9062]], eyes: [R62, [0.3398, 0.4805, 0.3203, 0.1211]], pivotL: [0.3691, 0.3936], pivotR: [0.6309, 0.3936] },
    { yaw: 32, body: [R63, [0.2148, 0.0625, 0.5625, 0.9141]], eyes: [R64, [0.4805, 0.4688, 0.2812, 0.1328]], pivotL: [0.3331, 0.4036], pivotR: [0.5575, 0.3873] },
    { yaw: 62, body: [R65, [0.2266, 0.0586, 0.543, 0.9219]], eyes: [R66, [0.6133, 0.4531, 0.1875, 0.1406]], pivotL: [0.3449, 0.4139], pivotR: [0.4738, 0.3864] },
  ],
  margo: [
    { yaw: 0, body: [R67, [0.1992, 0.0703, 0.6016, 0.9062]], eyes: [R68, [0.3398, 0.4805, 0.3203, 0.1211]], pivotL: [0.36, 0.3936], pivotR: [0.64, 0.3936] },
    { yaw: 32, body: [R69, [0.1992, 0.0625, 0.6328, 0.9141]], eyes: [R70, [0.4883, 0.4688, 0.2812, 0.1367]], pivotL: [0.325, 0.4041], pivotR: [0.5651, 0.3868] },
    { yaw: 62, body: [R71, [0.2148, 0.0586, 0.5898, 0.9219]], eyes: [R72, [0.6211, 0.4531, 0.1875, 0.1445]], pivotL: [0.3402, 0.4149], pivotR: [0.478, 0.3854] },
  ],
};
export const SHARED_VIEWS: Record<number, SharedView> = {
  0: { wingL: [R83, [0.0521, 0.2214, 0.3307, 0.2214]], wingR: [R84, [0.6406, 0.2214, 0.2839, 0.2214]], goldL: [R85, [0.0495, 0.2214, 0.3359, 0.224]], goldR: [R86, [0.6406, 0.2214, 0.2839, 0.224]], crown: [R87, [0.3464, 0.151, 0.3203, 0.2057]], pivotL: [0.3691, 0.3935], pivotR: [0.6309, 0.3935] },
  16: { wingL: [R88, [0.0365, 0.2292, 0.3151, 0.2266]], wingR: [R89, [0.6016, 0.2161, 0.276, 0.2161]], goldL: [R90, [0.0365, 0.2266, 0.3151, 0.2292]], goldR: [R91, [0.6016, 0.2161, 0.276, 0.2188]], crown: [R92, [0.3646, 0.1484, 0.3099, 0.2109]], pivotL: [0.3454, 0.3982], pivotR: [0.5977, 0.3898] },
  32: { wingL: [R78, [0.0573, 0.2344, 0.2708, 0.2344]], wingR: [R79, [0.5521, 0.2109, 0.2578, 0.2188]], goldL: [R80, [0.0573, 0.2344, 0.2734, 0.2344]], goldR: [R81, [0.5495, 0.2109, 0.2578, 0.2188]], crown: [R82, [0.3646, 0.1484, 0.3047, 0.2109]], pivotL: [0.3331, 0.4036], pivotR: [0.5575, 0.3873] },
  47: { wingL: [R93, [0.112, 0.2396, 0.2083, 0.2396]], wingR: [R94, [0.5, 0.2057, 0.2266, 0.2214]], goldL: [R95, [0.112, 0.2396, 0.2083, 0.2396]], goldR: [R96, [0.5, 0.2057, 0.2266, 0.224]], crown: [R97, [0.3646, 0.1484, 0.3021, 0.2109]], pivotL: [0.3332, 0.4088], pivotR: [0.5161, 0.3862] },
  62: { wingL: [R73, [0.1979, 0.2448, 0.1276, 0.2448]], wingR: [R74, [0.4505, 0.2031, 0.1797, 0.2266]], goldL: [R75, [0.1979, 0.2448, 0.1276, 0.2448]], goldR: [R76, [0.4505, 0.2005, 0.1797, 0.2292]], crown: [R77, [0.3594, 0.1484, 0.3099, 0.2109]], pivotL: [0.3449, 0.4139], pivotR: [0.4737, 0.3864] },
};
export const GARDEN_ART: Record<string, number> = {
  "clover_bloom": require("../../assets/art/garden/clover_bloom.webp"),
  "clover_bud": require("../../assets/art/garden/clover_bud.webp"),
  "cornflower_bloom": require("../../assets/art/garden/cornflower_bloom.webp"),
  "cornflower_bud": require("../../assets/art/garden/cornflower_bud.webp"),
  "lavender_bloom": require("../../assets/art/garden/lavender_bloom.webp"),
  "lavender_bud": require("../../assets/art/garden/lavender_bud.webp"),
  "mint_bloom": require("../../assets/art/garden/mint_bloom.webp"),
  "mint_bud": require("../../assets/art/garden/mint_bud.webp"),
  "nectar": require("../../assets/art/garden/nectar.webp"),
  "sprout": require("../../assets/art/garden/sprout.webp"),
  "sunflower_bloom": require("../../assets/art/garden/sunflower_bloom.webp"),
  "sunflower_bud": require("../../assets/art/garden/sunflower_bud.webp"),
};
