"""Packs the Blender renders into app assets (v1.2):
  assets/art/bees/*.webp   cropped layers (body, eyes, wings, gold wings, crown) per view
  assets/art/garden/*.webp low-poly flowers + nectar icon
  src/ui/beeArt.ts         generated requires + layer rectangles / anchors (fractions of the render frame)
  assets/icon.png, android-icon-foreground/monochrome, splash-icon, favicon, notification-icon (new low-poly Zhuzha)
Usage: python3 scripts/bees3d/pack.py /tmp/beer/bees /tmp/beer/flowers
"""
import json, os, sys, glob
from PIL import Image, ImageDraw, ImageFilter, ImageFont

BEES_DIR, FLOWERS_DIR = sys.argv[1], sys.argv[2]
OUT = "assets/art/bees"; GOUT = "assets/art/garden"
os.makedirs(OUT, exist_ok=True); os.makedirs(GOUT, exist_ok=True)
SPECIES = ["zhuzha", "pushinka", "boris", "solnyshko", "klevera", "lavanda", "vasilek", "myatka", "iskorka", "sonya", "zorkaya", "margo"]
total = 0

def crop_save(src, dst, q=85, scale=1.0):
    """crop to the alpha bbox (1px pad), optional downscale; returns rect as fractions of the frame."""
    global total
    im = Image.open(src).convert("RGBA")
    S = im.width
    a = im.getchannel("A").point(lambda v: 255 if v > 3 else 0)
    bb = a.getbbox()
    if not bb: return None
    x0, y0, x1, y1 = max(0, bb[0] - 1), max(0, bb[1] - 1), min(S, bb[2] + 1), min(S, bb[3] + 1)
    c = im.crop((x0, y0, x1, y1))
    if scale != 1.0:
        c = c.resize((max(1, round(c.width * scale)), max(1, round(c.height * scale))), Image.LANCZOS)
    c.save(dst, "WEBP", quality=q, method=6, alpha_quality=90)
    total += os.path.getsize(dst)
    return [round(x0 / S, 4), round(y0 / S, 4), round((x1 - x0) / S, 4), round((y1 - y0) / S, 4)]

def norm(p, S): return [round(p[0] / S, 4), round(p[1] / S, 4)]

req = []
def ref(path):
    req.append(path); return f"R{len(req) - 1}"

views = {}
for sp in SPECIES:
    vs = []
    for meta_f in sorted(glob.glob(f"{BEES_DIR}/{sp}_*.json"), key=lambda f: int(f.rsplit("_", 1)[1][:-5])):
        m = json.load(open(meta_f)); S = m["size"]; v = m["view"]; tag = f"{sp}_{v}"
        body = crop_save(f"{BEES_DIR}/{tag}_body.png", f"{OUT}/{tag}_body.webp")
        entry = {"yaw": v, "body": [ref(f"{tag}_body.webp"), body], "pivotL": norm(m["pivotL"], S), "pivotR": norm(m["pivotR"], S)}
        if os.path.exists(f"{BEES_DIR}/{tag}_eyes.png"):
            entry["eyes"] = [ref(f"{tag}_eyes.webp"), crop_save(f"{BEES_DIR}/{tag}_eyes.png", f"{OUT}/{tag}_eyes.webp", q=90)]
        vs.append(entry)
    views[sp] = vs

# shared wings / gold wings / crown (rendered on Zhuzha), per view
shared = {}
for meta_f in glob.glob(f"{BEES_DIR}/zhuzha_*.json"):
    m = json.load(open(meta_f)); S = m["size"]; v = m["view"]; tag = f"zhuzha_{v}"
    e = {}
    for k in ("wingL", "wingR", "goldL", "goldR", "crown"):
        # wings/crown are drawn smaller than the 384 frame in game: store them at 256-frame resolution
        r = crop_save(f"{BEES_DIR}/{tag}_{k}.png", f"{OUT}/shared_{v}_{k}.webp", q=88, scale=256 / S)
        e[k] = [ref(f"shared_{v}_{k}.webp"), r]
    e["pivotL"], e["pivotR"] = norm(m["pivotL"], S), norm(m["pivotR"], S)
    shared[v] = e
bee_bytes = total

# garden
total = 0
flowers = {}
for f in sorted(glob.glob(f"{FLOWERS_DIR}/*.png")):
    name = os.path.basename(f)[:-4]
    im = Image.open(f).convert("RGBA")
    im.save(f"{GOUT}/{name}.webp", "WEBP", quality=86, method=6, alpha_quality=90)
    total += os.path.getsize(f"{GOUT}/{name}.webp")
    flowers[name] = f"G_{name}"
garden_bytes = total

def js(o):
    return json.dumps(o).replace('"R', "R").replace('", [', ", [")
lines = ["/* AUTO-GENERATED by scripts/bees3d/pack.py from the Blender renders (scripts/bees3d/render_lowpoly.py). Do not edit. */",
         "/* eslint-disable @typescript-eslint/no-require-imports */",
         "export type Rect = [number, number, number, number]; // x, y, w, h as fractions of the render frame",
         "export type Layer = [number, Rect];",
         "export interface BeeView { yaw: number; body: Layer; eyes?: Layer; pivotL: [number, number]; pivotR: [number, number] }",
         "export interface SharedView { wingL: Layer; wingR: Layer; goldL: Layer; goldR: Layer; crown: Layer; pivotL: [number, number]; pivotR: [number, number] }"]
for i, p in enumerate(req):
    lines.append(f'const R{i} = require("../../assets/art/bees/{p}");')
def layer(l): return f"[{l[0]}, {json.dumps(l[1])}]"
lines.append("export const BEE_VIEWS: Record<string, BeeView[]> = {")
for sp, vs in views.items():
    lines.append(f"  {sp}: [")
    for e in vs:
        eyes = f", eyes: {layer(e['eyes'])}" if "eyes" in e else ""
        lines.append(f"    {{ yaw: {e['yaw']}, body: {layer(e['body'])}{eyes}, pivotL: {json.dumps(e['pivotL'])}, pivotR: {json.dumps(e['pivotR'])} }},")
    lines.append("  ],")
lines.append("};")
lines.append("export const SHARED_VIEWS: Record<number, SharedView> = {")
for v in sorted(shared):
    e = shared[v]
    lines.append(f"  {v}: {{ wingL: {layer(e['wingL'])}, wingR: {layer(e['wingR'])}, goldL: {layer(e['goldL'])}, goldR: {layer(e['goldR'])}, crown: {layer(e['crown'])}, pivotL: {json.dumps(e['pivotL'])}, pivotR: {json.dumps(e['pivotR'])} }},")
lines.append("};")
lines.append("export const GARDEN_ART: Record<string, number> = {")
for name in flowers:
    lines.append(f'  "{name}": require("../../assets/art/garden/{name}.webp"),')
lines.append("};")
open("src/ui/beeArt.ts", "w").write("\n".join(lines) + "\n")
print(f"bee layers: {len(req)} files, {bee_bytes/1024:.1f} KB; garden: {len(flowers)} files, {garden_bytes/1024:.1f} KB")

# ---------------- app icon / splash (low-poly Zhuzha) ----------------
def bee_fit(src, box):
    im = Image.open(src).convert("RGBA"); im = im.crop(im.getchannel("A").getbbox())
    k = box / max(im.size); im = im.resize((round(im.width * k), round(im.height * k)), Image.LANCZOS)
    out = im.copy(); out.alpha_composite(im); return out  # icons: double the translucent wings so they read on any background
I = 1024
FULL = f"{BEES_DIR}/icon/zhuzha_0_full.png"
bg = Image.open("assets/android-icon-background.png").convert("RGBA")
icon = bg.copy(); b = bee_fit(FULL, 800); icon.alpha_composite(b, ((I - b.width) // 2, (I - b.height) // 2 + 6))
icon.convert("RGB").save("assets/icon.png")
icon.resize((48, 48), Image.LANCZOS).convert("RGB").save("assets/favicon.png")
fg = Image.new("RGBA", (I, I)); b2 = bee_fit(FULL, 600); fg.alpha_composite(b2, ((I - b2.width) // 2, (I - b2.height) // 2 + 6))
fg.save("assets/android-icon-foreground.png", optimize=True)
def silhouette(im):
    a = im.getchannel("A").point(lambda v: 255 if v > 60 else 0)
    out = Image.new("RGBA", im.size, (255, 255, 255, 0)); out.putalpha(a); return out
mono = Image.new("RGBA", (I, I)); mono.alpha_composite(silhouette(b2), ((I - b2.width) // 2, (I - b2.height) // 2 + 6))
mono.save("assets/android-icon-monochrome.png", optimize=True)
S = 512
sp_ = Image.new("RGBA", (S, S)); bb = bee_fit(FULL, 270); sp_.alpha_composite(bb, ((S - bb.width) // 2, 312 - bb.height))
font = ImageFont.truetype("assets/fonts/Nunito-Black.ttf", 76); text = "Buzzle"
d = ImageDraw.Draw(sp_); l, t, r, bt = d.textbbox((0, 0), text, font=font); x, y = (S - (r - l)) // 2 - l, 318 - t
sh = Image.new("RGBA", (S, S)); ImageDraw.Draw(sh).text((x, y + 5), text, font=font, fill=(150, 80, 0, 110), stroke_width=7, stroke_fill=(150, 80, 0, 110))
sp_ = Image.alpha_composite(sh.filter(ImageFilter.GaussianBlur(3)), sp_)
ImageDraw.Draw(sp_).text((x, y), text, font=font, fill=(110, 58, 12, 255), stroke_width=7, stroke_fill=(255, 201, 74, 255))
sp_.save("assets/splash-icon.png", optimize=True)
nb = silhouette(bee_fit(FULL, 88)); n = Image.new("RGBA", (96, 96)); n.alpha_composite(nb, ((96 - nb.width) // 2, (96 - nb.height) // 2)); n.save("assets/notification-icon.png")
print("icons ok")
