"""Packs the Blender renders into app assets (v1.2):
  assets/art/bees/*.webp   cropped layers (body, eyes, wings, gold wings, crown) per view
  assets/art/garden/*.webp low-poly flowers + nectar icon
  src/ui/beeArt.ts         generated requires + layer rectangles / anchors (fractions of the render frame)
  assets/icon.png, android-icon-foreground/monochrome, splash-icon, favicon, notification-icon (new low-poly Zhuzha)
  v1.3: night bee, skin overlays per view (shared, like the crown), rare flowers, assets/art/items (decorations,
  surprise combs + wax-crack stages) → ITEM_ART
Usage: python3 scripts/bees3d/pack.py /tmp/beer/bees /tmp/beer/flowers [/tmp/beer/items]
"""
import json, os, sys, glob, math
from PIL import Image, ImageDraw, ImageFilter, ImageFont

BEES_DIR, FLOWERS_DIR = sys.argv[1], sys.argv[2]
ITEMS_DIR = sys.argv[3] if len(sys.argv) > 3 else None
SKINS = ["scarf", "bow", "glasses", "backpack", "wreath", "beret", "headphones", "halo"]
OUT = "assets/art/bees"; GOUT = "assets/art/garden"
os.makedirs(OUT, exist_ok=True); os.makedirs(GOUT, exist_ok=True)
SPECIES = ["zhuzha", "pushinka", "boris", "solnyshko", "klevera", "lavanda", "vasilek", "myatka", "iskorka", "sonya", "zorkaya", "margo", "nochka"]
total = 0

def crop_save(src, dst, q=85, scale=1.0):
    """crop to the alpha bbox (1px pad), optional downscale; returns rect as fractions of the frame."""
    global total
    im = Image.open(src).convert("RGBA")
    S = im.width
    a = im.getchannel("A").point(lambda v: 255 if v > 3 else 0)
    bb = a.getbbox()
    if not bb: return None
    x0, y0, x1, y1 = max(0, bb[0] - 1), max(0, bb[1] - 1), min(S, bb[2] + 1), min(S, bb[3] + 1)
    c = im.crop((x0, y0, x1, y1))
    if scale != 1.0:
        c = c.resize((max(1, round(c.width * scale)), max(1, round(c.height * scale))), Image.LANCZOS)
    c.save(dst, "WEBP", quality=q, method=6, alpha_quality=90)
    total += os.path.getsize(dst)
    return [round(x0 / S, 4), round(y0 / S, 4), round((x1 - x0) / S, 4), round((y1 - y0) / S, 4)]

def norm(p, S): return [round(p[0] / S, 4), round(p[1] / S, 4)]

req = []
def ref(path):
    req.append(path); return f"R{len(req) - 1}"

views = {}
for sp in SPECIES:
    vs = []
    for meta_f in sorted(glob.glob(f"{BEES_DIR}/{sp}_*.json"), key=lambda f: int(f.rsplit("_", 1)[1][:-5])):
        m = json.load(open(meta_f)); S = m["size"]; v = m["view"]; tag = f"{sp}_{v}"
        body = crop_save(f"{BEES_DIR}/{tag}_body.png", f"{OUT}/{tag}_body.webp")
        entry = {"yaw": v, "body": [ref(f"{tag}_body.webp"), body], "pivotL": norm(m["pivotL"], S), "pivotR": norm(m["pivotR"], S)}
        if os.path.exists(f"{BEES_DIR}/{tag}_eyes.png"):
            entry["eyes"] = [ref(f"{tag}_eyes.webp"), crop_save(f"{BEES_DIR}/{tag}_eyes.png", f"{OUT}/{tag}_eyes.webp", q=90)]
        vs.append(entry)
    views[sp] = vs

# shared wings / gold wings / crown (rendered on Zhuzha), per view
shared = {}
for meta_f in glob.glob(f"{BEES_DIR}/zhuzha_*.json"):
    m = json.load(open(meta_f)); S = m["size"]; v = m["view"]; tag = f"zhuzha_{v}"
    e = {}
    for k in ("wingL", "wingR", "goldL", "goldR", "crown"):
        # wings/crown are drawn smaller than the 384 frame in game: store them at 256-frame resolution
        r = crop_save(f"{BEES_DIR}/{tag}_{k}.png", f"{OUT}/shared_{v}_{k}.webp", q=88, scale=256 / S)
        e[k] = [ref(f"shared_{v}_{k}.webp"), r]
    e["skins"] = {}
    for k in SKINS:
        src = f"{BEES_DIR}/{tag}_skin_{k}.png"
        if os.path.exists(src):
            r = crop_save(src, f"{OUT}/skin_{v}_{k}.webp", q=86, scale=256 / S)
            if r: e["skins"][k] = [ref(f"skin_{v}_{k}.webp"), r]
    e["pivotL"], e["pivotR"] = norm(m["pivotL"], S), norm(m["pivotR"], S)
    shared[v] = e
bee_bytes = total

# garden
total = 0
flowers = {}
for f in sorted(glob.glob(f"{FLOWERS_DIR}/*.png")):
    name = os.path.basename(f)[:-4]
    im = Image.open(f).convert("RGBA")
    im.save(f"{GOUT}/{name}.webp", "WEBP", quality=86, method=6, alpha_quality=90)
    total += os.path.getsize(f"{GOUT}/{name}.webp")
    flowers[name] = f"G_{name}"
garden_bytes = total

def js(o):
    return json.dumps(o).replace('"R', "R").replace('", [', ", [")
lines = ["/* AUTO-GENERATED by scripts/bees3d/pack.py from the Blender renders (scripts/bees3d/render_lowpoly.py). Do not edit. */",
         "/* eslint-disable @typescript-eslint/no-require-imports */",
         "export type Rect = [number, number, number, number]; // x, y, w, h as fractions of the render frame",
         "export type Layer = [number, Rect];",
         "export interface BeeView { yaw: number; body: Layer; eyes?: Layer; pivotL: [number, number]; pivotR: [number, number] }",
         "export interface SharedView { wingL: Layer; wingR: Layer; goldL: Layer; goldR: Layer; crown: Layer; skins: Record<string, Layer>; pivotL: [number, number]; pivotR: [number, number] }"]
for i, p in enumerate(req):
    lines.append(f'const R{i} = require("../../assets/art/bees/{p}");')
def layer(l): return f"[{l[0]}, {json.dumps(l[1])}]"
lines.append("export const BEE_VIEWS: Record<string, BeeView[]> = {")
for sp, vs in views.items():
    lines.append(f"  {sp}: [")
    for e in vs:
        eyes = f", eyes: {layer(e['eyes'])}" if "eyes" in e else ""
        lines.append(f"    {{ yaw: {e['yaw']}, body: {layer(e['body'])}{eyes}, pivotL: {json.dumps(e['pivotL'])}, pivotR: {json.dumps(e['pivotR'])} }},")
    lines.append("  ],")
lines.append("};")
lines.append("export const SHARED_VIEWS: Record<number, SharedView> = {")
for v in sorted(shared):
    e = shared[v]
    sk = ", ".join(f"{k}: {layer(l)}" for k, l in e["skins"].items())
    lines.append(f"  {v}: {{ wingL: {layer(e['wingL'])}, wingR: {layer(e['wingR'])}, goldL: {layer(e['goldL'])}, goldR: {layer(e['goldR'])}, crown: {layer(e['crown'])}, skins: {{ {sk} }}, pivotL: {json.dumps(e['pivotL'])}, pivotR: {json.dumps(e['pivotR'])} }},")
lines.append("};")
lines.append("export const GARDEN_ART: Record<string, number> = {")
for name in flowers:
    lines.append(f'  "{name}": require("../../assets/art/garden/{name}.webp"),')
lines.append("};")

# ---------------- v1.3 items: decorations, surprise combs, wax-crack stages ----------------
item_bytes = 0
if ITEMS_DIR:
    IOUT = "assets/art/items"; os.makedirs(IOUT, exist_ok=True)
    items = {}
    def save_item(im, name, q=86):
        global item_bytes
        im.save(f"{IOUT}/{name}.webp", "WEBP", quality=q, method=6, alpha_quality=90)
        item_bytes += os.path.getsize(f"{IOUT}/{name}.webp")
        items[name] = im.size
    for f in sorted(glob.glob(f"{ITEMS_DIR}/deco_*.png")):
        name = os.path.basename(f)[:-4]
        im = Image.open(f).convert("RGBA"); im = im.crop(im.getchannel("A").point(lambda v: 255 if v > 3 else 0).getbbox())
        k = 168 / max(im.size); im = im.resize((max(1, round(im.width * k)), max(1, round(im.height * k))), Image.LANCZOS)
        save_item(im, name)
    # combs keep the whole (same) camera frame so the crack overlays line up on every kind
    B = 220; box_a = None
    for f in sorted(glob.glob(f"{ITEMS_DIR}/box_*.png")):
        name = os.path.basename(f)[:-4]
        im = Image.open(f).convert("RGBA").resize((B, B), Image.LANCZOS)
        if name == "box_wax": box_a = im.getchannel("A")
        save_item(im, name, q=88)
    if box_a is not None:
        # three crack stages drawn over the wax cap and the front faces (deterministic jagged lines)
        import random
        x0, y0, x1, y1 = box_a.getbbox()
        cx, cy = (x0 + x1) / 2, y0 + (y1 - y0) * 0.36
        rnd = random.Random(13)
        cracks = []
        for i in range(9):
            a = -math.pi / 2 + (i - 4) * 0.62 + rnd.uniform(-0.15, 0.15)
            pts = [(cx + rnd.uniform(-4, 4), cy + rnd.uniform(-3, 3))]
            L = rnd.uniform(0.26, 0.4) * (x1 - x0)
            for k in range(1, 6):
                t = k / 5; j = rnd.uniform(-0.35, 0.35)
                pts.append((pts[0][0] + math.cos(a + j) * L * t, pts[0][1] + math.sin(a + j) * L * t * 0.75 + (L * t * 0.5 if abs(a + math.pi / 2) > 1.2 else 0)))
            cracks.append(pts)
        for stage, n in ((1, 2), (2, 5), (3, 9)):
            ov = Image.new("RGBA", (B, B)); d = ImageDraw.Draw(ov)
            for pts in cracks[:n]:
                d.line(pts, fill=(90, 45, 5, 230), width=5, joint="curve")
            for pts in cracks[:n]:
                d.line(pts, fill=(255, 245, 200, 255), width=2, joint="curve")
            if stage == 3:
                glow = Image.new("RGBA", (B, B)); ImageDraw.Draw(glow).ellipse((cx - 34, cy - 24, cx + 34, cy + 24), fill=(255, 240, 160, 170))
                ov = Image.alpha_composite(glow.filter(ImageFilter.GaussianBlur(10)), ov)
            # keep the cracks on the comb only
            ov.putalpha(Image.composite(ov.getchannel("A"), Image.new("L", (B, B), 0), box_a.point(lambda v: 255 if v > 200 else 0)))
            save_item(ov, f"crack{stage}", q=90)
    lines.append("/** v1.3 items: decorations (cropped), surprise combs and wax-crack stages (full comb frame) */")
    lines.append("export const ITEM_ART: Record<string, { src: number; w: number; h: number }> = {")
    for name, (w, h) in items.items():
        lines.append(f'  "{name}": {{ src: require("../../assets/art/items/{name}.webp"), w: {w}, h: {h} }},')
    lines.append("};")
open("src/ui/beeArt.ts", "w").write("\n".join(lines) + "\n")
print(f"bee layers: {len(req)} files, {bee_bytes/1024:.1f} KB; garden: {len(flowers)} files, {garden_bytes/1024:.1f} KB; items: {item_bytes/1024:.1f} KB")

# ---------------- app icon / splash (low-poly Zhuzha) ----------------
def bee_fit(src, box):
    im = Image.open(src).convert("RGBA"); im = im.crop(im.getchannel("A").getbbox())
    k = box / max(im.size); im = im.resize((round(im.width * k), round(im.height * k)), Image.LANCZOS)
    out = im.copy(); out.alpha_composite(im); return out  # icons: double the translucent wings so they read on any background
I = 1024
FULL = f"{BEES_DIR}/icon/zhuzha_0_full.png"
bg = Image.open("assets/android-icon-background.png").convert("RGBA")
icon = bg.copy(); b = bee_fit(FULL, 800); icon.alpha_composite(b, ((I - b.width) // 2, (I - b.height) // 2 + 6))
icon.convert("RGB").save("assets/icon.png")
icon.resize((48, 48), Image.LANCZOS).convert("RGB").save("assets/favicon.png")
fg = Image.new("RGBA", (I, I)); b2 = bee_fit(FULL, 600); fg.alpha_composite(b2, ((I - b2.width) // 2, (I - b2.height) // 2 + 6))
fg.save("assets/android-icon-foreground.png", optimize=True)
def silhouette(im):
    a = im.getchannel("A").point(lambda v: 255 if v > 60 else 0)
    out = Image.new("RGBA", im.size, (255, 255, 255, 0)); out.putalpha(a); return out
mono = Image.new("RGBA", (I, I)); mono.alpha_composite(silhouette(b2), ((I - b2.width) // 2, (I - b2.height) // 2 + 6))
mono.save("assets/android-icon-monochrome.png", optimize=True)
S = 512
sp_ = Image.new("RGBA", (S, S)); bb = bee_fit(FULL, 270); sp_.alpha_composite(bb, ((S - bb.width) // 2, 312 - bb.height))
font = ImageFont.truetype("assets/fonts/Nunito-Black.ttf", 76); text = "Buzzle"
d = ImageDraw.Draw(sp_); l, t, r, bt = d.textbbox((0, 0), text, font=font); x, y = (S - (r - l)) // 2 - l, 318 - t
sh = Image.new("RGBA", (S, S)); ImageDraw.Draw(sh).text((x, y + 5), text, font=font, fill=(150, 80, 0, 110), stroke_width=7, stroke_fill=(150, 80, 0, 110))
sp_ = Image.alpha_composite(sh.filter(ImageFilter.GaussianBlur(3)), sp_)
ImageDraw.Draw(sp_).text((x, y), text, font=font, fill=(110, 58, 12, 255), stroke_width=7, stroke_fill=(255, 201, 74, 255))
sp_.save("assets/splash-icon.png", optimize=True)
nb = silhouette(bee_fit(FULL, 88)); n = Image.new("RGBA", (96, 96)); n.alpha_composite(nb, ((96 - nb.width) // 2, (96 - nb.height) // 2)); n.save("assets/notification-icon.png")
print("icons ok")
