"""Generate src/ui/tabIconData.ts: the four tab icons pre-tinted (active white / inactive brown) as inline
PNG data URIs for the web build. Inline data never touches the network and needs no SVG tint filter, so
the tab bar can remount (e.g. after a puzzle round) without the icons ever going blank."""
import base64, io
from PIL import Image
TINTS = {"on": (255, 255, 255), "off": (0xC4, 0x9A, 0x62)}
out = ["// generated by scripts/make_tab_icons_web.py — do not edit", "export const TAB_ICON_DATA: Record<string, { on: string; off: string }> = {"]
for tab, f in (("hive", "tab_hive"), ("puzzle", "tab_puzzle"), ("bees", "tab_bee"), ("tasks", "tab_tasks")):
    im = Image.open(f"assets/art/{f}.png").convert("RGBA").resize((78, 78), Image.LANCZOS)  # 26 pt @3x
    a = im.getchannel("A")
    parts = []
    for k, c in TINTS.items():
        t = Image.new("RGBA", im.size, (*c, 0)); t.putalpha(a)
        b = io.BytesIO(); t.save(b, "PNG", optimize=True)
        parts.append(f'{k}: "data:image/png;base64,{base64.b64encode(b.getvalue()).decode()}"')
    out.append(f"  {tab}: {{ {', '.join(parts)} }},")
out.append("};")
open("src/ui/tabIconData.ts", "w").write("\n".join(out) + "\n")
print("tab icons:", sum(len(l) for l in out), "chars")
